#' Function for convert DMUs generated by make_rdsDMU() into FITS format
#'
#' @description Takes a catalogue generated using make_rdsDMU() and make it into a sensible FITS binary table.
#'
#' @param DMU Object generated by make_rdsDMU()
#' @return a FITS file with the format: DMUName,'_',format(Sys.time(), "%d_%m_%Y"),'_v',version,'.fits'
#' @author L. Davies <luke.j.davies@uwa.edu>
#' @examples
# MUName<-'dummy'
# cat<-data.frame(col1=round(runif(10,1,10)), col2=runif(10,0,360), col3=runif(10,-90,90))
# summary<-'This is my catalogue, with things in it that I measured'
#usrGen<-'G. M. Bluth'
#contactGen<-'g.m.bluth@thebluthfamily.com'
#scriptGen<-'myScript.R'
#version<-0.1
#coldescription<-c('This is column1, it has column1-like things in it - maybe an ID', 'This is column2, supprisingly it has column2-like things in it - maybe an RA', 'This is column2, supprisingly it has column2-like things in it - maybe a DEC' )
#colucd<-c('meta.id', 'pos.eq.ra', 'pos.eq.dec')
#colunits<-c('none', 'deg', 'deg')
#README<-c('The is a README that describes this table. I can put in lots of information about hot the catalogue is generated and its providance. If I wane to start a new line, I should use \n. Or I can skip lines with \n\n. This way if someone wants to read it, they can easily do cat(DMU$README)')
#DMU<-make_rdsDMU(DMUName, cat, summary, usrGen, contactGen, scriptGen, version, coldescription,  colucd, colunits, README, test=TRUE)
#rdsToFitsDMU(DMU)
#' @export
rdsToFitsDMU<-function(DMU){


  cat('Formatting table..... \n')
  primaryKeyNames<-c(names(DMU$meta)[1:7], names(DMU$meta$RGen))
  primaryKeyValues<-c(DMU$meta[[2]],DMU$meta[[3]],DMU$meta[[4]],DMU$meta[[5]],DMU$meta[[6]],DMU$meta[[7]], DMU$meta[[8]], unlist(DMU$meta[[9]]))
  primaryKeyCom<-c('Table Summary', 'User who generated table', 'contact details of user', 'script used to generate table', 'version number of DMU table', 'date DMU was generated', 'machine used to generate table', 'platform of machine', 'architechture of machine', 'Operating System of machine', 'Full system of machine', 'status of machine', 'R version used (Major)', 'R version used (Minor)', 'Year of R version', 'Month of R version','Day of R version','svn rev', 'Coding language used', 'Full version striong of R code', 'Nickname of R version used')
  primaryHdr<-data.frame(ext=0,keyvalues=primaryKeyValues,keycomments=primaryKeyCom, keynames=primaryKeyNames)

  ex1KeyNames<-c('EXTNAME','TFIELDS')
  ex1KeyValues<-data.frame(DMU$meta$name,length(DMU$colnames))
  ex1KeyCom<-c('extension name','number of table fields')

  tform<-unlist(lapply(DMU$cat, class))
  tform[which(tform=='double')]<-'1D'
  tform[which(tform=='numeric')]<-'1D'
  tform[which(tform=='integer')]<-'1J'
  tform[which(tform=='character')]<-'16A'
  tform[which(tform=='factor')]<-'16A'

  TUNIT<-c()
  for (i in 1:length(DMU$colnames)){
    
    if (unlist(lapply(DMU$cat, class))[i]=='factor'){
      DMU$cat[,i]<-as.character(DMU$cat[,i])
    }
        
    ex1KeyNames<-c(ex1KeyNames, paste('TTYPE',i,sep='') , paste('TUCD',i,sep=''), paste('TCOMM',i,sep=''), paste('TNULL',i,sep=''))
    TNULL <- -999.9
    if (tform[i]=='1J'){TNULL <- -999}
    if (tform[i]=='16A'){TNULL <- ''}
    
    ex1KeyValues<-cbind(ex1KeyValues, DMU$colnames[i], DMU$colucd[i], DMU$coldescription[i], TNULL)
    ex1KeyCom<-c(ex1KeyCom, paste('Label for field ',i,sep=''), paste('UCD for field ',i,sep=''), paste('Comment for field ',i,sep=''), paste('Null value for field ',i,sep=''))
    TUNIT<-c(TUNIT, DMU$colunits[i])
    }



  ex1Hdr<-data.frame(ext=1,keyvalues=ex1KeyValues,keycomments=ex1KeyCom, keynames=ex1KeyNames)
  fileName<-paste(DMU$meta$name,'_',format(Sys.time(), "%d_%m_%Y"),'_v',DMU$meta$version,'.fits',sep='')

  cat('Writing table..... \n')
  Rfits_write_table(DMU$cat, fileName, ext = 2, extname = DMU$meta$name, tunits = TUNIT, create_ext = TRUE, create_file = TRUE,overwrite_file = TRUE, table_type = 'binary', NA_replace = -999.9, NaN_replace = -999.9, Inf_replace = -999.9, tforms=tform)


  cat('Adding secondary header..... \n')
  for (i in 1:length(ex1KeyNames)){
    tmp<-as.matrix(ex1KeyValues[[i]])[1,1]
    Rfits_write_key(fileName, as.character(ex1KeyNames[[i]]), tmp, keycomment = as.character(ex1KeyCom[[i]]), ext = 2)
  }
  cat('Adding srimary header..... \n')
  for (i in 1:length(primaryKeyNames)){
    tmp<-as.matrix(primaryKeyValues[[i]])[1,1]
    Rfits_write_key(fileName, as.character(primaryKeyNames[[i]]), tmp, keycomment = as.character(primaryKeyCom[[i]]), ext = 1)
  }

  cat('Writing checksum..... \n')
  Rfits_write_chksum(fileName)
  
  cat('Done! \n')

}
